### ISSUE TITLE
How to download 1h candles

### ISSUE THREAD

**Issue by Crypto7816** [kieran-mackle/ccxt-download#6]
I use the code bellow to download 1h candles, but the options paraters cannot be passed in.
```python
public.download(
                exchange="bybit",
                data_types=[CANDLES],
                symbols=[symbol],
                start_date="2023-01-01",
                end_date="2024-05-05",
                download_dir='/data/ccxt_data',
                options={"timeframe": "1h"}
            )
```

**Comment by Crypto7816** [comment]
> I use the code bellow to download 1h candles, but the options paraters cannot be passed in.
> 
> ```python
> public.download(
>                 exchange="bybit",
>                 data_types=[CANDLES],
>                 symbols=[symbol],
>                 start_date="2023-01-01",
>                 end_date="2024-05-05",
>                 download_dir='/data/ccxt_data',
>                 options={"timeframe": "1h"}
>             )
> ```

I read the code and fine the solutions, btw, great project:

```python
            public.download(
                exchange="binance",
                data_types=[CANDLES],
                symbols=[symbol],
                start_date="2023-01-01",
                end_date="2024-05-05",
                download_dir='/data/ccxt_data',
                options={CANDLES: {"timeframe": "1h"}}
            )
 ```

**Comment by kieran-mackle** [comment]
Nice, thanks!
