### ISSUE TITLE
fail to download BTC/USDT:USDT okx {"msg":"Too Many Requests","code":"50011"}

### ISSUE THREAD

**Issue by Crypto7816** [kieran-mackle/ccxt-download#7]
Cannot download the funding rate data in okx, the bug message is `{"msg":"Too Many Requests","code":"50011"}`
```python
from ccxt_download import public, CANDLES, FUNDING
import pickle
from typing import Literal, Dict

def load_data(filename):
    # Load data from a pickle file
    with open(filename, 'rb') as f:
        return pickle.load(f)

def main(type: Literal['spot', 'linear'], exchange: str):
    # symbols = markets[type]
    symbols = ['BTC/USDT:USDT']
    for symbol in symbols:
        try:
            public.download(
                exchange=exchange,
                data_types=[FUNDING],
                symbols=[symbol],
                start_date="2023-01-01",
                end_date="2024-05-05",
                options={CANDLES: {"timeframe": "1h"}}
            )
        except Exception as e:
            print(f"fail to download {symbol} {e}")
    
if __name__ == "__main__":
    exchange = 'okx'
    main(type='linear', exchange=exchange)
```

**Comment by kieran-mackle** [comment]
I haven't tested the following, but playing around with the async rate limit should help here.

```python
from aiolimiter import AsyncLimiter

# < your code here >

public.download(
    exchange=exchange,
    data_types=[FUNDING],
    symbols=[symbol],
    start_date="2023-01-01",
    end_date="2024-05-05",
    rate_limiter=AsyncLimiter(max_rate=1, time_period=1),
)

# ...
```

I imagine the above will take a long time to download since it is a long time range. The package is also not currently optimised to do funding rate downloads, since it would likely be easier to just make a single request with a larger range, versus what the package does, walking forward by a single day at a time.

**Comment by Crypto7816** [comment]
> I haven't tested the following, but playing around with the async rate limit should help here.
> 
> ```python
> from aiolimiter import AsyncLimiter
> 
> # < your code here >
> 
> public.download(
>     exchange=exchange,
>     data_types=[FUNDING],
>     symbols=[symbol],
>     start_date="2023-01-01",
>     end_date="2024-05-05",
>     rate_limiter=AsyncLimiter(max_rate=1, time_period=1),
> )
> 
> # ...
> ```
> 
> I imagine the above will take a long time to download since it is a long time range. The package is also not currently optimised to do funding rate downloads, since it would likely be easier to just make a single request with a larger range, versus what the package does, walking forward by a single day at a time.
I tried the code you gave me, but it stuck and wouldn't download. I want to know if you can use this code to download
```python
from ccxt_download import public, CANDLES, FUNDING
import pickle
from typing import Literal, Dict
from aiolimiter import AsyncLimiter

# Default download path 
# DEFAULT_DOWNLOAD_DIR = os.path.join(os.path.expanduser("~"), ".ccxt_data")

def load_data(filename):
    # Load data from a pickle file
    with open(filename, 'rb') as f:
        return pickle.load(f)

def main(type: Literal['spot', 'linear'], markets: Dict, exchange: str):
    symbols = markets[type]
    # symbols = ['BTC/USDT:USDT']
    for symbol in symbols:
        try:
            public.download(
                exchange=exchange,
                data_types=[FUNDING],
                symbols=[symbol],
                start_date="2023-01-01",
                end_date="2024-05-05",
                rate_limiter=AsyncLimiter(max_rate=1, time_period=1),
                # options={CANDLES: {"timeframe": "1h"}}
            )
        except Exception as e:
            print(f"fail to download {symbol} {e}")
    
if __name__ == "__main__":
    exchange = 'okx'
    markets = load_data(f"symbols/{exchange}_markets.pkl")
    main(type='linear', markets=markets, exchange=exchange)
```

**Comment by Crypto7816** [comment]
> I haven't tested the following, but playing around with the async rate limit should help here.
> 
> ```python
> from aiolimiter import AsyncLimiter
> 
> # < your code here >
> 
> public.download(
>     exchange=exchange,
>     data_types=[FUNDING],
>     symbols=[symbol],
>     start_date="2023-01-01",
>     end_date="2024-05-05",
>     rate_limiter=AsyncLimiter(max_rate=1, time_period=1),
> )
> 
> # ...
> ```
> 
> I imagine the above will take a long time to download since it is a long time range. The package is also not currently optimised to do funding rate downloads, since it would likely be easier to just make a single request with a larger range, versus what the package does, walking forward by a single day at a time.

Great, it worked. I ve tested the okx api, the maxium rate conpactity for download is `AsyncLimiter(max_rate=5, time_period=2)`
